INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (1,'albert_park','Albert Park Grand Prix Circuit','Melbourne','Australia');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (2,'sepang','Sepang International Circuit','Kuala Lumpur','Malaysia');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (3,'bahrain','Bahrain International Circuit','Sakhir','Bahrain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (4,'catalunya','Circuit de Barcelona-Catalunya','Montmeló','Spain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (5,'istanbul','Istanbul Park','Istanbul','Turkey');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (6,'monaco','Circuit de Monaco','Monte-Carlo','Monaco');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (7,'villeneuve','Circuit Gilles Villeneuve','Montreal','Canada');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (8,'magny_cours','Circuit de Nevers Magny-Cours','Magny Cours','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (9,'silverstone','Silverstone Circuit','Silverstone','UK');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (10,'hockenheimring','Hockenheimring','Hockenheim','Germany');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (11,'hungaroring','Hungaroring','Budapest','Hungary');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (12,'valencia','Valencia Street Circuit','Valencia','Spain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (13,'spa','Circuit de Spa-Francorchamps','Spa','Belgium');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (14,'monza','Autodromo Nazionale di Monza','Monza','Italy');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (15,'marina_bay','Marina Bay Street Circuit','Marina Bay','Singapore');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (16,'fuji','Fuji Speedway','Oyama','Japan');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (17,'shanghai','Shanghai International Circuit','Shanghai','China');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (18,'interlagos','Autódromo José Carlos Pace','São Paulo','Brazil');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (19,'indianapolis','Indianapolis Motor Speedway','Indianapolis','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (20,'nurburgring','Nürburgring','Nürburg','Germany');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (21,'imola','Autodromo Enzo e Dino Ferrari','Imola','Italy');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (22,'suzuka','Suzuka Circuit','Suzuka','Japan');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (23,'osterreichring','A1-Ring','Spielburg','Austria');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (24,'yas_marina','Yas Marina Circuit','Abu Dhabi','UAE');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (25,'galvez','Autódromo Juan y Oscar Gálvez','Buenos Aires','Argentina');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (26,'jerez','circuitos de Jerez','Jerez de la Frontera','Spain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (27,'estoril','Autódromo do Estoril','Estoril','Portugal');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (28,'okayama','Okayama International Circuit','Okayama','Japan');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (29,'adelaide','Adelaide Street Circuit','Adelaide','Australia');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (30,'kyalami','Kyalami','Midrand','South Africa');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (31,'donington','Donington Park','Castle Donington','UK');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (32,'rodriguez','Autódromo Hermanos Rodríguez','Mexico City','Mexico');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (33,'phoenix','Phoenix street circuit','Phoenix','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (34,'ricard','Circuit Paul Ricard','Le Castellet','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (35,'yeongam','Korean International Circuit','Yeongam County','Korea');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (36,'jacarepagua','Autódromo Internacional Nelson Piquet','Rio de Janeiro','Brazil');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (37,'detroit','Detroit Street Circuit','Detroit','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (38,'brands_hatch','Brands Hatch','Kent','UK');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (39,'zandvoort','Circuit Park Zandvoort','Zandvoort','Netherlands');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (40,'zolder','Zolder','Heusden-Zolder','Belgium');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (41,'dijon','Dijon-Prenois','Dijon','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (42,'dallas','Fair Park','Dallas','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (43,'long_beach','Long Beach','California','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (44,'las_vegas','Las Vegas Street Circuit','Nevada','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (45,'jarama','Jarama','Madrid','Spain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (46,'watkins_glen','Watkins Glen','New York State','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (47,'anderstorp','Scandinavian Raceway','Anderstorp','Sweden');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (48,'mosport','Mosport International Raceway','Ontario','Canada');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (49,'montjuic','Montjuïc','Barcelona','Spain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (50,'nivelles','Nivelles-Baulers','Brussels','Belgium');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (51,'charade','Charade Circuit','Clermont-Ferrand','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (52,'tremblant','Circuit Mont-Tremblant','Quebec','Canada');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (53,'essarts','Rouen-Les-Essarts','Rouen','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (54,'lemans','Le Mans','Le Mans','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (55,'reims','Reims-Gueux','Reims','France');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (56,'george','Prince George Circuit','Eastern Cape Province','South Africa');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (57,'zeltweg','Zeltweg','Styria','Austria');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (58,'aintree','Aintree','Liverpool','UK');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (59,'boavista','circuitos da Boavista','Oporto','Portugal');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (60,'riverside','Riverside International Raceway','California','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (61,'avus','AVUS','Berlin','Germany');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (62,'monsanto','Monsanto Park Circuit','Lisbon','Portugal');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (63,'sebring','Sebring International Raceway','Florida','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (64,'ain-diab','Ain Diab','Casablanca','Morocco');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (65,'pescara','Pescara Circuit','Pescara','Italy');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (66,'bremgarten','Circuit Bremgarten','Bern','Switzerland');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (67,'pedralbes','Circuit de Pedralbes','Barcelona','Spain');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (68,'buddh','Buddh International Circuit','Uttar Pradesh','India');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (69,'americas','Circuit of the Americas','Austin','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (70,'red_bull_ring','Red Bull Ring','Spielburg','Austria');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (71,'sochi','Sochi Autodrom','Sochi','Russia');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (72,'port_imperial','Port Imperial Street Circuit','New Jersey','USA');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (73,'BAK','Baku City Circuit','Baku','Azerbaijan');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (74,'hanoi','Hanoi Street Circuit','Hanoi','Vietnam');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (75,'portimao','Autódromo Internacional do Algarve','Portimão','Portugal');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (76,'mugello','Autodromo Internazionale del Mugello','Mugello','Italy');		
INSERT INTO circuitos (id_circuito, ref_circuito, nome_circuito, location_circuito, pais_circuito) VALUES (77,'jeddah','Jeddah Street Circuit','Jeddah','Saudi Arabia');		
