/* SCRIPT PARA CRIAÇÃO DOS CONSTRUTORES*/
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (1,'McLaren','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (2,'BMW Sauber','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (3,'Williams','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (4,'Renault','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (5,'Toro Rosso','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (6,'Ferrari','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (7,'Toyota','Japanese');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (8,'Super Aguri','Japanese');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (9,'Red Bull','Austrian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (10,'Force India','Indian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (11,'Honda','Japanese');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (12,'Spyker','Dutch');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (13,'MF1','Russian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (14,'Spyker MF1','Dutch');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (15,'Sauber','Swiss');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (16,'BAR','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (17,'Jordan','Irish');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (18,'Minardi','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (19,'Jaguar','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (20,'Prost','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (21,'Arrows','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (22,'Benetton','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (23,'Brawn','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (24,'Stewart','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (25,'Tyrrell','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (26,'Lola','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (27,'Ligier','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (28,'Forti','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (29,'Footwork','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (30,'Pacific','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (31,'Simtek','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (32,'Team Lotus','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (33,'Larrousse','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (34,'Brabham','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (35,'Dallara','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (36,'Fondmetal','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (37,'March','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (38,'Andrea Moda','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (39,'AGS','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (40,'Lambo','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (41,'Leyton House','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (42,'Coloni','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (44,'Euro Brun','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (45,'Osella','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (46,'Onyx','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (47,'Life','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (48,'Rial','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (49,'Zakspeed','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (50,'RAM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (51,'Alfa Romeo','Swiss');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (52,'Spirit','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (53,'Toleman','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (54,'ATS','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (55,'Theodore','Hong Kong');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (56,'Fittipaldi','Brazilian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (57,'Ensign','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (58,'Shadow','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (59,'Wolf','Canadian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (60,'Merzario','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (61,'Kauhsen','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (62,'Rebaque','Mexican');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (63,'Surtees','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (64,'Hesketh','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (65,'Martini','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (66,'BRM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (67,'Penske','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (68,'LEC','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (69,'McGuire','Australian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (70,'Boro','Dutch');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (71,'Apollon','Swiss');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (72,'Kojima','Japanese');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (73,'Parnelli','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (74,'Maki','Japanese');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (75,'Embassy Hill','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (76,'Lyncar','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (77,'Trojan','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (78,'Amon','New Zealand');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (79,'Token','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (80,'Iso Marlboro','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (81,'Tecno','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (82,'Matra','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (83,'Politoys','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (84,'Connew','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (85,'Bellasi','Swiss');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (86,'De Tomaso','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (87,'Cooper','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (88,'Eagle','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (89,'LDS','South African');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (90,'Protos','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (91,'Shannon','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (92,'Scirocco','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (93,'RE','Rhodesian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (94,'BRP','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (95,'Porsche','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (96,'Derrington','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (97,'Gilby','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (98,'Stebro','Canadian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (99,'Emeryson','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (100,'ENB','Belgium');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (101,'JBW','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (102,'Ferguson','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (103,'MBM','Swiss');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (104,'Behra-Porsche','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (105,'Maserati','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (106,'Scarab','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (107,'Watson','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (108,'Epperly','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (109,'Phillips','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (110,'Lesovsky','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (111,'Trevis','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (112,'Meskowski','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (113,'Kurtis Kraft','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (114,'Kuzma','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (115,'Christensen','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (116,'Ewing','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (117,'Aston Martin','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (118,'Vanwall','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (119,'Moore','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (120,'Dunn','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (121,'Elder','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (122,'Sutton','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (123,'Fry','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (124,'Tec-Mec','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (125,'Connaught','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (126,'Alta','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (127,'OSCA','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (128,'Gordini','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (129,'Stevens','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (130,'Bugatti','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (131,'Mercedes','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (132,'Lancia','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (133,'HWM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (134,'Schroeder','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (135,'Pawl','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (136,'Pankratz','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (137,'Arzani-Volpini','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (138,'Nichels','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (139,'Bromme','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (140,'Klenk','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (141,'Simca','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (142,'Turner','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (143,'Del Roy','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (144,'Veritas','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (145,'BMW','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (146,'EMW','East German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (147,'AFM','German');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (148,'Frazer Nash','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (149,'Sherman','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (150,'Deidt','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (151,'ERA','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (152,'Aston Butterworth','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (153,'Cisitalia','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (154,'Talbot-Lago','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (155,'Hall','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (156,'Marchese','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (157,'Langley','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (158,'Rae','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (159,'Olson','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (160,'Wetteroth','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (161,'Adams','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (162,'Snowberger','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (163,'Milano','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (164,'HRT','Spanish');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (167,'Cooper-Maserati','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (166,'Virgin','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (168,'Cooper-OSCA','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (169,'Cooper-Borgward','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (170,'Cooper-Climax','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (171,'Cooper-Castellotti','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (172,'Lotus-Climax','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (173,'Lotus-Maserati','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (174,'De Tomaso-Osca','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (175,'De Tomaso-Alfa Romeo','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (176,'Lotus-BRM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (177,'Lotus-Borgward','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (178,'Cooper-Alfa Romeo','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (179,'De Tomaso-Ferrari','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (180,'Lotus-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (181,'Brabham-BRM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (182,'Brabham-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (183,'Brabham-Climax','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (184,'LDS-Climax','South African');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (185,'LDS-Alfa Romeo','South African');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (186,'Cooper-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (187,'McLaren-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (188,'McLaren-Serenissima','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (189,'Eagle-Climax','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (190,'Eagle-Weslake','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (191,'Brabham-Repco','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (192,'Cooper-Ferrari','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (193,'Cooper-ATS','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (194,'McLaren-BRM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (195,'Cooper-BRM','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (196,'Matra-Ford','French');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (197,'BRM-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (198,'McLaren-Alfa Romeo','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (199,'March-Alfa Romeo','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (200,'March-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (201,'Lotus-Pratt & Whitney','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (202,'Shadow-Ford','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (203,'Shadow-Matra','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (204,'Brabham-Alfa Romeo','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (205,'Lotus','Malaysian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (206,'Marussia','Russian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (207,'Caterham','Malaysian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (208,'Lotus F1','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (209,'Manor Marussia','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (210,'Haas F1 Team','American');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (211,'Racing Point','British');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (213,'AlphaTauri','Italian');
INSERT INTO construtores (id_construtor, nome_construtor, nacionalidade_construtor) VALUES (214,'Alpine F1 Team','French');
