ALTER TABLE `FORMULA1`.`construtores` 
ADD COLUMN `fabricante_motor` VARCHAR(45) NOT NULL AFTER `nacionalidade_construtor`;

ALTER TABLE `formula1`.`construtores` 
CHANGE COLUMN `fabricante_motor` `fabricante_motor` VARCHAR(45) NOT NULL AFTER `nome_construtor`;


update construtores set fabricante_motor = 'Mercedes' WHERE id_construtor =1;
update construtores set fabricante_motor = 'BMW Sauber' WHERE id_construtor =2;
update construtores set fabricante_motor = 'Mercedes' WHERE id_construtor =3;
update construtores set fabricante_motor = 'Renault' WHERE id_construtor =4;
update construtores set fabricante_motor = 'Toro Rosso' WHERE id_construtor =5;
update construtores set fabricante_motor = 'Ferrari' WHERE id_construtor =6;
update construtores set fabricante_motor = 'Toyota' WHERE id_construtor =7;
update construtores set fabricante_motor = 'Super Aguri' WHERE id_construtor =8;
update construtores set fabricante_motor = 'Honda' WHERE id_construtor =9;
update construtores set fabricante_motor = 'Force India' WHERE id_construtor =10;
update construtores set fabricante_motor = 'Honda' WHERE id_construtor =11;
update construtores set fabricante_motor = 'Spyker' WHERE id_construtor =12;
update construtores set fabricante_motor = 'MF1' WHERE id_construtor =13;
update construtores set fabricante_motor = 'Spyker MF1' WHERE id_construtor =14;
update construtores set fabricante_motor = 'Sauber' WHERE id_construtor =15;
update construtores set fabricante_motor = 'BAR' WHERE id_construtor =16;
update construtores set fabricante_motor = 'Jordan' WHERE id_construtor =17;
update construtores set fabricante_motor = 'Minardi' WHERE id_construtor =18;
update construtores set fabricante_motor = 'Jaguar' WHERE id_construtor =19;
update construtores set fabricante_motor = 'Prost' WHERE id_construtor =20;
update construtores set fabricante_motor = 'Arrows' WHERE id_construtor =21;
update construtores set fabricante_motor = 'Benetton' WHERE id_construtor =22;
update construtores set fabricante_motor = 'Brawn' WHERE id_construtor =23;
update construtores set fabricante_motor = 'Stewart' WHERE id_construtor =24;
update construtores set fabricante_motor = 'Tyrrell' WHERE id_construtor =25;
update construtores set fabricante_motor = 'Lola' WHERE id_construtor =26;
update construtores set fabricante_motor = 'Ligier' WHERE id_construtor =27;
update construtores set fabricante_motor = 'Forti' WHERE id_construtor =28;
update construtores set fabricante_motor = 'Footwork' WHERE id_construtor =29;
update construtores set fabricante_motor = 'Pacific' WHERE id_construtor =30;
update construtores set fabricante_motor = 'Simtek' WHERE id_construtor =31;
update construtores set fabricante_motor = 'Team Lotus' WHERE id_construtor =32;
update construtores set fabricante_motor = 'Larrousse' WHERE id_construtor =33;
update construtores set fabricante_motor = 'Brabham' WHERE id_construtor =34;
update construtores set fabricante_motor = 'Dallara' WHERE id_construtor =35;
update construtores set fabricante_motor = 'Fondmetal' WHERE id_construtor =36;
update construtores set fabricante_motor = 'March' WHERE id_construtor =37;
update construtores set fabricante_motor = 'Andrea Moda' WHERE id_construtor =38;
update construtores set fabricante_motor = 'AGS' WHERE id_construtor =39;
update construtores set fabricante_motor = 'Lambo' WHERE id_construtor =40;
update construtores set fabricante_motor = 'Leyton House' WHERE id_construtor =41;
update construtores set fabricante_motor = 'Coloni' WHERE id_construtor =42;
update construtores set fabricante_motor = 'Euro Brun' WHERE id_construtor =44;
update construtores set fabricante_motor = 'Osella' WHERE id_construtor =45;
update construtores set fabricante_motor = 'Onyx' WHERE id_construtor =46;
update construtores set fabricante_motor = 'Life' WHERE id_construtor =47;
update construtores set fabricante_motor = 'Rial' WHERE id_construtor =48;
update construtores set fabricante_motor = 'Zakspeed' WHERE id_construtor =49;
update construtores set fabricante_motor = 'RAM' WHERE id_construtor =50;
update construtores set fabricante_motor = 'Ferrari' WHERE id_construtor =51;
update construtores set fabricante_motor = 'Spirit' WHERE id_construtor =52;
update construtores set fabricante_motor = 'Toleman' WHERE id_construtor =53;
update construtores set fabricante_motor = 'ATS' WHERE id_construtor =54;
update construtores set fabricante_motor = 'Theodore' WHERE id_construtor =55;
update construtores set fabricante_motor = 'Fittipaldi' WHERE id_construtor =56;
update construtores set fabricante_motor = 'Ensign' WHERE id_construtor =57;
update construtores set fabricante_motor = 'Shadow' WHERE id_construtor =58;
update construtores set fabricante_motor = 'Wolf' WHERE id_construtor =59;
update construtores set fabricante_motor = 'Merzario' WHERE id_construtor =60;
update construtores set fabricante_motor = 'Kauhsen' WHERE id_construtor =61;
update construtores set fabricante_motor = 'Rebaque' WHERE id_construtor =62;
update construtores set fabricante_motor = 'Surtees' WHERE id_construtor =63;
update construtores set fabricante_motor = 'Hesketh' WHERE id_construtor =64;
update construtores set fabricante_motor = 'Martini' WHERE id_construtor =65;
update construtores set fabricante_motor = 'BRM' WHERE id_construtor =66;
update construtores set fabricante_motor = 'Penske' WHERE id_construtor =67;
update construtores set fabricante_motor = 'LEC' WHERE id_construtor =68;
update construtores set fabricante_motor = 'McGuire' WHERE id_construtor =69;
update construtores set fabricante_motor = 'Boro' WHERE id_construtor =70;
update construtores set fabricante_motor = 'Apollon' WHERE id_construtor =71;
update construtores set fabricante_motor = 'Kojima' WHERE id_construtor =72;
update construtores set fabricante_motor = 'Parnelli' WHERE id_construtor =73;
update construtores set fabricante_motor = 'Maki' WHERE id_construtor =74;
update construtores set fabricante_motor = 'Embassy Hill' WHERE id_construtor =75;
update construtores set fabricante_motor = 'Lyncar' WHERE id_construtor =76;
update construtores set fabricante_motor = 'Trojan' WHERE id_construtor =77;
update construtores set fabricante_motor = 'Amon' WHERE id_construtor =78;
update construtores set fabricante_motor = 'Token' WHERE id_construtor =79;
update construtores set fabricante_motor = 'Iso Marlboro' WHERE id_construtor =80;
update construtores set fabricante_motor = 'Tecno' WHERE id_construtor =81;
update construtores set fabricante_motor = 'Matra' WHERE id_construtor =82;
update construtores set fabricante_motor = 'Politoys' WHERE id_construtor =83;
update construtores set fabricante_motor = 'Connew' WHERE id_construtor =84;
update construtores set fabricante_motor = 'Bellasi' WHERE id_construtor =85;
update construtores set fabricante_motor = 'De Tomaso' WHERE id_construtor =86;
update construtores set fabricante_motor = 'Cooper' WHERE id_construtor =87;
update construtores set fabricante_motor = 'Eagle' WHERE id_construtor =88;
update construtores set fabricante_motor = 'LDS' WHERE id_construtor =89;
update construtores set fabricante_motor = 'Protos' WHERE id_construtor =90;
update construtores set fabricante_motor = 'Shannon' WHERE id_construtor =91;
update construtores set fabricante_motor = 'Scirocco' WHERE id_construtor =92;
update construtores set fabricante_motor = 'RE' WHERE id_construtor =93;
update construtores set fabricante_motor = 'BRP' WHERE id_construtor =94;
update construtores set fabricante_motor = 'Porsche' WHERE id_construtor =95;
update construtores set fabricante_motor = 'Derrington' WHERE id_construtor =96;
update construtores set fabricante_motor = 'Gilby' WHERE id_construtor =97;
update construtores set fabricante_motor = 'Stebro' WHERE id_construtor =98;
update construtores set fabricante_motor = 'Emeryson' WHERE id_construtor =99;
update construtores set fabricante_motor = 'ENB' WHERE id_construtor =100;
update construtores set fabricante_motor = 'JBW' WHERE id_construtor =101;
update construtores set fabricante_motor = 'Ferguson' WHERE id_construtor =102;
update construtores set fabricante_motor = 'MBM' WHERE id_construtor =103;
update construtores set fabricante_motor = 'Porsche' WHERE id_construtor =104;
update construtores set fabricante_motor = 'Maserati' WHERE id_construtor =105;
update construtores set fabricante_motor = 'Scarab' WHERE id_construtor =106;
update construtores set fabricante_motor = 'Watson' WHERE id_construtor =107;
update construtores set fabricante_motor = 'Epperly' WHERE id_construtor =108;
update construtores set fabricante_motor = 'Phillips' WHERE id_construtor =109;
update construtores set fabricante_motor = 'Lesovsky' WHERE id_construtor =110;
update construtores set fabricante_motor = 'Trevis' WHERE id_construtor =111;
update construtores set fabricante_motor = 'Meskowski' WHERE id_construtor =112;
update construtores set fabricante_motor = 'Kurtis Kraft' WHERE id_construtor =113;
update construtores set fabricante_motor = 'Kuzma' WHERE id_construtor =114;
update construtores set fabricante_motor = 'Christensen' WHERE id_construtor =115;
update construtores set fabricante_motor = 'Ewing' WHERE id_construtor =116;
update construtores set fabricante_motor = 'Aston Martin' WHERE id_construtor =117;
update construtores set fabricante_motor = 'Vanwall' WHERE id_construtor =118;
update construtores set fabricante_motor = 'Moore' WHERE id_construtor =119;
update construtores set fabricante_motor = 'Dunn' WHERE id_construtor =120;
update construtores set fabricante_motor = 'Elder' WHERE id_construtor =121;
update construtores set fabricante_motor = 'Sutton' WHERE id_construtor =122;
update construtores set fabricante_motor = 'Fry' WHERE id_construtor =123;
update construtores set fabricante_motor = 'Mec' WHERE id_construtor =124;
update construtores set fabricante_motor = 'Connaught' WHERE id_construtor =125;
update construtores set fabricante_motor = 'Alta' WHERE id_construtor =126;
update construtores set fabricante_motor = 'OSCA' WHERE id_construtor =127;
update construtores set fabricante_motor = 'Gordini' WHERE id_construtor =128;
update construtores set fabricante_motor = 'Stevens' WHERE id_construtor =129;
update construtores set fabricante_motor = 'Bugatti' WHERE id_construtor =130;
update construtores set fabricante_motor = 'Mercedes' WHERE id_construtor =131;
update construtores set fabricante_motor = 'Lancia' WHERE id_construtor =132;
update construtores set fabricante_motor = 'HWM' WHERE id_construtor =133;
update construtores set fabricante_motor = 'Schroeder' WHERE id_construtor =134;
update construtores set fabricante_motor = 'Pawl' WHERE id_construtor =135;
update construtores set fabricante_motor = 'Pankratz' WHERE id_construtor =136;
update construtores set fabricante_motor = 'Volpini' WHERE id_construtor =137;
update construtores set fabricante_motor = 'Nichels' WHERE id_construtor =138;
update construtores set fabricante_motor = 'Bromme' WHERE id_construtor =139;
update construtores set fabricante_motor = 'Klenk' WHERE id_construtor =140;
update construtores set fabricante_motor = 'Simca' WHERE id_construtor =141;
update construtores set fabricante_motor = 'Turner' WHERE id_construtor =142;
update construtores set fabricante_motor = 'Del Roy' WHERE id_construtor =143;
update construtores set fabricante_motor = 'Veritas' WHERE id_construtor =144;
update construtores set fabricante_motor = 'BMW' WHERE id_construtor =145;
update construtores set fabricante_motor = 'EMW' WHERE id_construtor =146;
update construtores set fabricante_motor = 'AFM' WHERE id_construtor =147;
update construtores set fabricante_motor = 'Frazer Nash' WHERE id_construtor =148;
update construtores set fabricante_motor = 'Sherman' WHERE id_construtor =149;
update construtores set fabricante_motor = 'Deidt' WHERE id_construtor =150;
update construtores set fabricante_motor = 'ERA' WHERE id_construtor =151;
update construtores set fabricante_motor = 'Mercedes' WHERE id_construtor =152;
update construtores set fabricante_motor = 'Cisitalia' WHERE id_construtor =153;
update construtores set fabricante_motor = 'Lago' WHERE id_construtor =154;
update construtores set fabricante_motor = 'Hall' WHERE id_construtor =155;
update construtores set fabricante_motor = 'Marchese' WHERE id_construtor =156;
update construtores set fabricante_motor = 'Langley' WHERE id_construtor =157;
update construtores set fabricante_motor = 'Rae' WHERE id_construtor =158;
update construtores set fabricante_motor = 'Olson' WHERE id_construtor =159;
update construtores set fabricante_motor = 'Wetteroth' WHERE id_construtor =160;
update construtores set fabricante_motor = 'Adams' WHERE id_construtor =161;
update construtores set fabricante_motor = 'Snowberger' WHERE id_construtor =162;
update construtores set fabricante_motor = 'Milano' WHERE id_construtor =163;
update construtores set fabricante_motor = 'HRT' WHERE id_construtor =164;
update construtores set fabricante_motor = 'Virgin' WHERE id_construtor =166;
update construtores set fabricante_motor = 'Maserati' WHERE id_construtor =167;
update construtores set fabricante_motor = 'OSCA' WHERE id_construtor =168;
update construtores set fabricante_motor = 'Borgward' WHERE id_construtor =169;
update construtores set fabricante_motor = 'Climax' WHERE id_construtor =170;
update construtores set fabricante_motor = 'Castellotti' WHERE id_construtor =171;
update construtores set fabricante_motor = 'Climax' WHERE id_construtor =172;
update construtores set fabricante_motor = 'Maserati' WHERE id_construtor =173;
update construtores set fabricante_motor = 'Osca' WHERE id_construtor =174;
update construtores set fabricante_motor = 'Alfa Romeo' WHERE id_construtor =175;
update construtores set fabricante_motor = 'BRM' WHERE id_construtor =176;
update construtores set fabricante_motor = 'Borgward' WHERE id_construtor =177;
update construtores set fabricante_motor = 'Alfa Romeo' WHERE id_construtor =178;
update construtores set fabricante_motor = 'Ferrari' WHERE id_construtor =179;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =180;
update construtores set fabricante_motor = 'BRM' WHERE id_construtor =181;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =182;
update construtores set fabricante_motor = 'Climax' WHERE id_construtor =183;
update construtores set fabricante_motor = 'Climax' WHERE id_construtor =184;
update construtores set fabricante_motor = 'Alfa Romeo' WHERE id_construtor =185;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =186;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =187;
update construtores set fabricante_motor = 'Serenissima' WHERE id_construtor =188;
update construtores set fabricante_motor = 'Climax' WHERE id_construtor =189;
update construtores set fabricante_motor = 'Weslake' WHERE id_construtor =190;
update construtores set fabricante_motor = 'Repco' WHERE id_construtor =191;
update construtores set fabricante_motor = 'Ferrari' WHERE id_construtor =192;
update construtores set fabricante_motor = 'ATS' WHERE id_construtor =193;
update construtores set fabricante_motor = 'BRM' WHERE id_construtor =194;
update construtores set fabricante_motor = 'BRM' WHERE id_construtor =195;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =196;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =197;
update construtores set fabricante_motor = 'Alfa Romeo' WHERE id_construtor =198;
update construtores set fabricante_motor = 'Alfa Romeo' WHERE id_construtor =199;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =200;
update construtores set fabricante_motor = 'Pratt &amp; Whitney' WHERE id_construtor =201;
update construtores set fabricante_motor = 'Ford' WHERE id_construtor =202;
update construtores set fabricante_motor = 'Matra' WHERE id_construtor =203;
update construtores set fabricante_motor = 'Alfa Romeo' WHERE id_construtor =204;
update construtores set fabricante_motor = 'Lotus' WHERE id_construtor =205;
update construtores set fabricante_motor = 'Marussia' WHERE id_construtor =206;
update construtores set fabricante_motor = 'Caterham' WHERE id_construtor =207;
update construtores set fabricante_motor = 'Lotus F1' WHERE id_construtor =208;
update construtores set fabricante_motor = 'Manor Marussia' WHERE id_construtor =209;
update construtores set fabricante_motor = 'Ferrari' WHERE id_construtor =210;
update construtores set fabricante_motor = 'Racing Point' WHERE id_construtor =211;
update construtores set fabricante_motor = 'Honda' WHERE id_construtor =213;
update construtores set fabricante_motor = 'Renault' WHERE id_construtor =214;
