INSERT INTO status (id_status, descricao_status) VALUES (1,'Finished');
INSERT INTO status (id_status, descricao_status) VALUES (2,'Disqualified');
INSERT INTO status (id_status, descricao_status) VALUES (3,'Accident');
INSERT INTO status (id_status, descricao_status) VALUES (4,'Collision');
INSERT INTO status (id_status, descricao_status) VALUES (5,'Engine');
INSERT INTO status (id_status, descricao_status) VALUES (6,'Gearbox');
INSERT INTO status (id_status, descricao_status) VALUES (7,'Transmission');
INSERT INTO status (id_status, descricao_status) VALUES (8,'Clutch');
INSERT INTO status (id_status, descricao_status) VALUES (9,'Hydraulics');
INSERT INTO status (id_status, descricao_status) VALUES (10,'Electrical');
INSERT INTO status (id_status, descricao_status) VALUES (11,'+1 Lap');
INSERT INTO status (id_status, descricao_status) VALUES (12,'+2 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (13,'+3 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (14,'+4 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (15,'+5 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (16,'+6 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (17,'+7 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (18,'+8 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (19,'+9 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (20,'Spun off');
INSERT INTO status (id_status, descricao_status) VALUES (21,'Radiator');
INSERT INTO status (id_status, descricao_status) VALUES (22,'Suspension');
INSERT INTO status (id_status, descricao_status) VALUES (23,'Brakes');
INSERT INTO status (id_status, descricao_status) VALUES (24,'Differential');
INSERT INTO status (id_status, descricao_status) VALUES (25,'Overheating');
INSERT INTO status (id_status, descricao_status) VALUES (26,'Mechanical');
INSERT INTO status (id_status, descricao_status) VALUES (27,'Tyre');
INSERT INTO status (id_status, descricao_status) VALUES (28,'Driver Seat');
INSERT INTO status (id_status, descricao_status) VALUES (29,'Puncture');
INSERT INTO status (id_status, descricao_status) VALUES (30,'Driveshaft');
INSERT INTO status (id_status, descricao_status) VALUES (31,'Retired');
INSERT INTO status (id_status, descricao_status) VALUES (32,'Fuel pressure');
INSERT INTO status (id_status, descricao_status) VALUES (33,'Front wing');
INSERT INTO status (id_status, descricao_status) VALUES (34,'Water pressure');
INSERT INTO status (id_status, descricao_status) VALUES (35,'Refuelling');
INSERT INTO status (id_status, descricao_status) VALUES (36,'Wheel');
INSERT INTO status (id_status, descricao_status) VALUES (37,'Throttle');
INSERT INTO status (id_status, descricao_status) VALUES (38,'Steering');
INSERT INTO status (id_status, descricao_status) VALUES (39,'Technical');
INSERT INTO status (id_status, descricao_status) VALUES (40,'Electronics');
INSERT INTO status (id_status, descricao_status) VALUES (41,'Broken wing');
INSERT INTO status (id_status, descricao_status) VALUES (42,'Heat shield fire');
INSERT INTO status (id_status, descricao_status) VALUES (43,'Exhaust');
INSERT INTO status (id_status, descricao_status) VALUES (44,'Oil leak');
INSERT INTO status (id_status, descricao_status) VALUES (45,'+11 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (46,'Wheel rim');
INSERT INTO status (id_status, descricao_status) VALUES (47,'Water leak');
INSERT INTO status (id_status, descricao_status) VALUES (48,'Fuel pump');
INSERT INTO status (id_status, descricao_status) VALUES (49,'Track rod');
INSERT INTO status (id_status, descricao_status) VALUES (50,'+17 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (51,'Oil pressure');
INSERT INTO status (id_status, descricao_status) VALUES (128,'+42 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (53,'+13 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (54,'Withdrew');
INSERT INTO status (id_status, descricao_status) VALUES (55,'+12 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (56,'Engine fire');
INSERT INTO status (id_status, descricao_status) VALUES (129,'Engine misfire');
INSERT INTO status (id_status, descricao_status) VALUES (58,'+26 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (59,'Tyre puncture');
INSERT INTO status (id_status, descricao_status) VALUES (60,'Out of fuel');
INSERT INTO status (id_status, descricao_status) VALUES (61,'Wheel nut');
INSERT INTO status (id_status, descricao_status) VALUES (62,'Not classified');
INSERT INTO status (id_status, descricao_status) VALUES (63,'Pneumatics');
INSERT INTO status (id_status, descricao_status) VALUES (64,'Handling');
INSERT INTO status (id_status, descricao_status) VALUES (65,'Rear wing');
INSERT INTO status (id_status, descricao_status) VALUES (66,'Fire');
INSERT INTO status (id_status, descricao_status) VALUES (67,'Wheel bearing');
INSERT INTO status (id_status, descricao_status) VALUES (68,'Physical');
INSERT INTO status (id_status, descricao_status) VALUES (69,'Fuel system');
INSERT INTO status (id_status, descricao_status) VALUES (70,'Oil line');
INSERT INTO status (id_status, descricao_status) VALUES (71,'Fuel rig');
INSERT INTO status (id_status, descricao_status) VALUES (72,'Launch control');
INSERT INTO status (id_status, descricao_status) VALUES (73,'Injured');
INSERT INTO status (id_status, descricao_status) VALUES (74,'Fuel');
INSERT INTO status (id_status, descricao_status) VALUES (75,'Power loss');
INSERT INTO status (id_status, descricao_status) VALUES (76,'Vibrations');
INSERT INTO status (id_status, descricao_status) VALUES (77,'107% Rule');
INSERT INTO status (id_status, descricao_status) VALUES (78,'Safety');
INSERT INTO status (id_status, descricao_status) VALUES (79,'Drivetrain');
INSERT INTO status (id_status, descricao_status) VALUES (80,'Ignition');
INSERT INTO status (id_status, descricao_status) VALUES (81,'Did not qualify');
INSERT INTO status (id_status, descricao_status) VALUES (82,'Injury');
INSERT INTO status (id_status, descricao_status) VALUES (83,'Chassis');
INSERT INTO status (id_status, descricao_status) VALUES (84,'Battery');
INSERT INTO status (id_status, descricao_status) VALUES (85,'Stalled');
INSERT INTO status (id_status, descricao_status) VALUES (86,'Halfshaft');
INSERT INTO status (id_status, descricao_status) VALUES (87,'Crankshaft');
INSERT INTO status (id_status, descricao_status) VALUES (88,'+10 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (89,'Safety concerns');
INSERT INTO status (id_status, descricao_status) VALUES (90,'Not restarted');
INSERT INTO status (id_status, descricao_status) VALUES (91,'Alternator');
INSERT INTO status (id_status, descricao_status) VALUES (92,'Underweight');
INSERT INTO status (id_status, descricao_status) VALUES (93,'Safety belt');
INSERT INTO status (id_status, descricao_status) VALUES (94,'Oil pump');
INSERT INTO status (id_status, descricao_status) VALUES (95,'Fuel leak');
INSERT INTO status (id_status, descricao_status) VALUES (96,'Excluded');
INSERT INTO status (id_status, descricao_status) VALUES (97,'Did not prequalify');
INSERT INTO status (id_status, descricao_status) VALUES (98,'Injection');
INSERT INTO status (id_status, descricao_status) VALUES (99,'Distributor');
INSERT INTO status (id_status, descricao_status) VALUES (100,'Driver unwell');
INSERT INTO status (id_status, descricao_status) VALUES (101,'Turbo');
INSERT INTO status (id_status, descricao_status) VALUES (102,'CV joint');
INSERT INTO status (id_status, descricao_status) VALUES (103,'Water pump');
INSERT INTO status (id_status, descricao_status) VALUES (104,'Fatal accident');
INSERT INTO status (id_status, descricao_status) VALUES (105,'Spark plugs');
INSERT INTO status (id_status, descricao_status) VALUES (106,'Fuel pipe');
INSERT INTO status (id_status, descricao_status) VALUES (107,'Eye injury');
INSERT INTO status (id_status, descricao_status) VALUES (108,'Oil pipe');
INSERT INTO status (id_status, descricao_status) VALUES (109,'Axle');
INSERT INTO status (id_status, descricao_status) VALUES (110,'Water pipe');
INSERT INTO status (id_status, descricao_status) VALUES (111,'+14 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (112,'+15 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (113,'+25 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (114,'+18 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (115,'+22 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (116,'+16 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (117,'+24 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (118,'+29 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (119,'+23 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (120,'+21 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (121,'Magneto');
INSERT INTO status (id_status, descricao_status) VALUES (122,'+44 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (123,'+30 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (124,'+19 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (125,'+46 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (126,'Supercharger');
INSERT INTO status (id_status, descricao_status) VALUES (127,'+20 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (130,'Collision damage');
INSERT INTO status (id_status, descricao_status) VALUES (131,'Power Unit');
INSERT INTO status (id_status, descricao_status) VALUES (132,'ERS');
INSERT INTO status (id_status, descricao_status) VALUES (133,'+49 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (134,'+38 Laps');
INSERT INTO status (id_status, descricao_status) VALUES (135,'Brake duct');
INSERT INTO status (id_status, descricao_status) VALUES (136,'Seat');
INSERT INTO status (id_status, descricao_status) VALUES (137,'Damage');
INSERT INTO status (id_status, descricao_status) VALUES (138,'Debris');
INSERT INTO status (id_status, descricao_status) VALUES (139,'Illness');
